authapp/urls.py
from django.urls import path
from authapp import views
from authapp.apps import AuthappConfig
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile_edit/<int:pk>/", views.ProfileEditView.as_view(), name="profile_edit"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("mainapp/", include("mainapp.urls", namespace='mainapp')),
    path("authapp/", include("authapp.urls", namespace="authapp")),
    path("social_auth/", include("social_django.urls", namespace='social'))
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path, include
from mainapp import views
from mainapp.apps import MainappConfig
from django.views.decorators.cache import cache_page

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("news/", views.newsListView, name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/detail",views.NewsDetailView.as_view(),name="news_detail",),
    path("news/<int:pk>/update",views.NewsUpdateView.as_view(),name="news_update",),
    path("news/<int:pk>/delete",views.NewsDeleteView.as_view(),name="news_delete",),
    # path("courses/",cache_page(60 * 5)(views.CoursesListView.as_view()),name="courses",),
    path("courses/",views.CoursesListView.as_view(),name="courses",),
    path("courses/<int:pk>/",views.CoursesDetailView.as_view(),name="courses_detail",),
    path("course_feedback/",views.CourseFeedbackFormProcessView.as_view(),name="course_feedback",),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
    path("log_view/", views.LogView.as_view(), name="log_view"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
    ]

    

mainapp/models.py
from tabnanny import verbose
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

class News(models.Model):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    preambule = models.CharField(max_length=1024, verbose_name="Вступление")
    body = models.TextField(blank=True, null=True, verbose_name="Основной текст")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Новости")
        verbose_name_plural = _("Новости")
        ordering = ("-created",)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}" #pk- primary key

    def delete(self, *args):
        self.deleted = True
        self.save()




class CoursesManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class Courses(models.Model):
    objects = CoursesManager()
    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = ('Курс')
        verbose_name_plural = ('Курсы')

class Lesson(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course.name} | {self.num} | {self.title}"
    
    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        ordering = ("course", "num")

class CourseTeachers(models.Model):
    course = models.ManyToManyField(Courses)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)
    
    def delete(self, *args):
        self.deleted = True
        self.save()

class CourseFeedback(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("User"))
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name=_("Course"))
    feedback = models.TextField(default=_("No feedback"), verbose_name=_("Feedback"))

    RATING = ((5, "⭐⭐⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (3, "⭐⭐⭐"), (2, "⭐⭐"),(1, "⭐"))
    rating = models.SmallIntegerField(choices=RATING, default=5, verbose_name=_("Rating"))
    
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    deleted = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.course} ({self.user})"

mainapp/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from mainapp import models as mainapp_models

class CourseFeedbackForm(forms.ModelForm):

    def __init__(self, *args, course=None, user=None, **kwargs):
        ret = super().__init__(*args, **kwargs)
        if course and user:
            self.fields["course"].initial = course.pk
            self.fields["user"].initial = user.pk
            return ret
            
    class Meta:
        model = mainapp_models.CourseFeedback
        fields = ("course", "user", "feedback", "rating")
        widgets = {
        "course": forms.HiddenInput(),
        "user": forms.HiddenInput(),
        "rating": forms.RadioSelect(),
        }

class MailFeedbackForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput)
    message = forms.CharField(widget=forms.Textarea, help_text=_("Enter your message"), label=_("Message"),)
    
    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields["user_id"].initial = user.pk

mainapp/views.py
from mainapp import models as mainapp_models
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, View, ListView, CreateView, DetailView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from mainapp import forms as mainapp_forms
from django.http import JsonResponse
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import FileResponse, JsonResponse
from config import settings
from mainapp import tasks as mainapp_tasks
from django.http.response import HttpResponseRedirect
import logging
from django.conf import settings
from django.contrib import messages
from django.core.cache import cache
from django.utils.translation import gettext_lazy as _
from mainapp import forms as mainapp_forms
from mainapp import models as mainapp_models
from django.core.paginator import Paginator
from django.shortcuts import render



logger = logging.getLogger(__name__)

class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class NewsPageView(TemplateView):
    template_name = "mainapp/news.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["news_qs"] = mainapp_models.News.objects.all()[:5]
        return context

class NewsPageDetailView(TemplateView):
    template_name = "mainapp/news_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        context = super().get_context_data(pk=pk, **kwargs)
        context["news_object"] = get_object_or_404(mainapp_models.News, pk=pk)
        return context


# class NewsListView(ListView):
#     template_name = 'mainapp/news.html'
#     model = mainapp_models.News
#     paginate_by = 5

#     def get_queryset(self):
#         return super().get_queryset().filter(deleted=False)

def newsListView(request):
    model = mainapp_models.News
    contact_list = model.objects.all()
    paginator = Paginator(contact_list, 5) 

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'mainapp/news.html', {'page_obj': page_obj})





class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = mainapp_models.News
    fields = "__all__" # использование всех полей
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.add_news",) # PermissionRequiredMixin проверять, предоставляются ли пользователю права для создания  новостей

class NewsDetailView(DetailView):
    model = mainapp_models.News

class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = mainapp_models.News
    fields = "__all__"
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.change_news",)

class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = mainapp_models.News
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.delete_news",)


class CoursesListView(TemplateView):
    template_name = "mainapp/courses_list.html"
    # paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(CoursesListView, self).get_context_data(**kwargs)
        context["objects"] = mainapp_models.Courses.objects.all()
        
        return context

class CoursesDetailView(TemplateView):
    template_name = "mainapp/courses_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context["course_object"] = get_object_or_404(mainapp_models.Courses, pk=pk)
        context["lessons"] = mainapp_models.Lesson.objects.filter(course=context["course_object"])
        context["teachers"] = mainapp_models.CourseTeachers.objects.filter(
        course=context["course_object"])
        if not self.request.user.is_anonymous:
            if not mainapp_models.CourseFeedback.objects.filter(
                course=context["course_object"], user=self.request.user).count():
                context["feedback_form"] = mainapp_forms.CourseFeedbackForm(course=context["course_object"], user=self.request.user)
        context["feedback_list"] = mainapp_models.CourseFeedback.objects.filter(
            course=context["course_object"]).order_by("-created", "-rating")[:5]
        return context

class CourseFeedbackFormProcessView(LoginRequiredMixin, CreateView):
    model = mainapp_models.CourseFeedback
    form_class = mainapp_forms.CourseFeedbackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_card = render_to_string("mainapp/includes/feedback_card.html", context={"item": self.object})
        return JsonResponse({"card": rendered_card})


class ContactsPageView(TemplateView):
    template_name = "mainapp/contacts.html"

    def get_context_data(self, **kwargs):
        context = super(ContactsPageView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["form"] = mainapp_forms.MailFeedbackForm(user=self.request.user)
        return context

    def post(self, *args, **kwargs):
        print(self.request.POST)
        if self.request.user.is_authenticated:
            cache_lock_flag = cache.get(f"mail_feedback_lock_{self.request.user.pk}")
            if not cache_lock_flag:
                cache.set(f"mail_feedback_lock_{self.request.user.pk}", "lock",timeout=300,)
                
                messages.add_message(self.request, messages.INFO, _("Message sended"))
                
                mainapp_tasks.send_feedback_mail.delay(
                    {
                    "user_id": self.request.POST.get("user_id"),
                    "message": self.request.POST.get("message"),
                    }
                )
            else:
                messages.add_message(self.request, messages.WARNING,
                _("You can send only one message per 5 minutes"),
                )
        return HttpResponseRedirect(reverse_lazy("mainapp:contacts"))

class DocSitePageView(TemplateView):
    template_name = "mainapp/doc_site.html"

class LogView(TemplateView):
    template_name = "mainapp/log_view.html"

    def get_context_data(self, **kwargs):
        context = super(LogView, self).get_context_data(**kwargs)
        log_slice = []
        with open(settings.LOG_FILE, "r") as log_file:
            for i, line in enumerate(log_file):
                if i == 1000:
                    break
                log_slice.insert(0, line)
                context["log"] = "".join(log_slice)
        return context

class LogDownloadView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, "rb"))

mainapp/templates/includes/base.html
{% load static %}


<!doctype html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">
    <title>Welcome to Braniac!</title>
</head>

<body>

    {% include 'includes/head_menu.html' %}
    {% block content %}

    <p>Нет контента страници</p>

    {% endblock content %}
    {% include 'includes/foot_menu.html' %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>
</body>

</html>

mainapp/templates/includes/feedback_card.html
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ item.get_rating_display }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ item.user }}</h6>
        <p class="card-text">
            {{ item.feedback }}
        </p>
    </div>
</div>

mainapp/templates/includes/foot_menu.html
<div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Braniac</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="index.html">Домашняя</a></li>
                <li><a href="news.html">Новости</a></li>
                <li><a href="login.html">Войти</a></li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Полезное</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="#">Положения &amp; Условия</a></li>
                <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                <li><a href="#">Документация по API</a></li>
                <li><a href="doc_site.html">Документация по сайту</a></li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Мы в социальных сетях</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
            </div>
            </p>
            <p>
                <strong>Наше приложение</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
            </div>
            </p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div>
            <p><small>&copy; GeekBrains 2021</small></p>
        </div>
    </div>
</div>

mainapp/templates/includes/head_menu.html
{% load static i18n %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:main_page' %}">
            <img src="/static/img/logo.png" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li
                    class="nav-item {% if request.resolver_match.view_name == 'mainapp:mainapp.views.News' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:news' %}">{% translate "Новости" %}</a>
                </li>

                <li
                    class="nav-item {% if request.resolver_match.view_name == 'mainapp:mainapp.views.Courses' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:courses' %}">{% translate "Курсы" %}</a>
                </li>

                </li>

                <li
                    class="nav-item {% if request.resolver_match.view_name == 'mainapp:mainapp.views.ContactsPageView' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:contacts' %}">{% translate "Контакты" %}</a>
                </li>
                {% if user.is_active %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {% translate Профиль %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="ddProfile">
                        <a class="dropdown-item" href="{% url 'authapp:profile_edit' pk=request.user.pk %} ">{%
                            translate "Редактировать профиль" %}</a>

                        <a class="dropdown-item" href="{% url 'mainapp:courses' %}">Мои курсы</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Модерация</a>

                        <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">{% translate "Страница
                            администартора" %}</a>
                        <a class="dropdown-item" href="{% url 'mainapp:log_view' %}" target="_blank">{% translate "Логи"
                            %}</a>

                    </div>
                </li>
                <a class="nav-link" href="{% url 'authapp:logout' %}">{% translate "Выход" %}</a>
                {% else %}
                <a class="nav-link" href="{% url 'authapp:login' %}">{% translate "Вход" %}</a>
                {% endif %}
            </ul>
            <div class="row justify-content-end m-0">
                <div class="col p-0 border-right">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="language" , value="ru"><button class="btn btn-link"
                            type="submit">🇷🇺</button>

                    </form>
                </div>
                <div class="col p-0 border-left">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="language" , value="en"><button class="btn btn-link"
                            type="submit">🇬🇧</button>
                    </form>
                </div>
            </div>




        </div>
    </div>
</nav>

mainapp/templates/includes/paginator.html
<div class="row justify-content-center align-items-center mt-3 mb-n3">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            </li>
            {% endif %}
            {% for item in page_obj.paginator.page_range %}
            <li class="page-item
{% if item == page_obj.number %}active{% endif %}">
                <a class="page-link" href="?page={{ item }}">{{ item }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a></li>
            {% endif %}
        </ul>
    </nav>
</div>